<!-- Filename: /module/Album/view/album/list/index.phtml -->
<h1>Albums</h1>

<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>Artist</th>
        <th>Title</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->albums as $a) : ?>
        <tr>
            <td><?php echo $a->getId();?></td>
            <td><?php echo $a->getArtist();?></td>
            <td><?php echo $a->getTitle();?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>