<!-- Filename: /module/Blog/view/blog/write/add.phtml -->
<h1>WriteController::editAction()</h1>
<?php
$form = $this->form;
$form->setAttribute('method', 'POST');
$form->setAttribute('action', $this->url('blog/edit', array(), true));
$form->prepare();

$form->get('submit')->setValue('Update Blog');

echo $this->form()->openTag($form);

echo $this->formCollection($form);

echo $this->form()->closeTag();